### ISSUE TITLE
Can't download from an input.txt where I stored the URLs

### ISSUE THREAD

**Issue by G9512** [obskyr/khinsider#10]

**Comment by obskyr** [comment]
Eh? Reading lines from a file isn't a feature of `khinsider.py`, is it?

If you're on Linux, you could do:

```bash
while read url; do
    python khinsider.py $url
done < input.txt
```

On Windows, you could do:

```bat
for /F "tokens=*" %%A in (input.txt) do python khinsider.py %%A
```

**Comment by G9512** [comment]
Thank you so much for the reply, I am in windows but I'm a dumb with coding. Should I write this in the command line as it is? Thank you again!

Il giorno 19 set 2016, alle ore 15:03, obskyr <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Eh? Reading lines from a file isn't a feature of khinsider.py, is it?

If you're on Linux, you could do:

while read url; do
    python khinsider.py $url
done < input.txt

On Windows, you could do:

for /F "tokens=*" %%A in (input.txt) do python khinsider.py %%A

-

**Comment by G9512** [comment]
When I type "khinsider.py for /F "tokens=*" %%A in (input.txt) do python khinsider.py %%A"
The code doesn't work, it says "The  soundtrack "for" doesn't seem to exist"

**Comment by G9512** [comment]
Ok now it works, I've created a .bat and then I called it but it's stuck at "getting song list..."
Can you merge this feature in the script? Maybe with the full url support?

**Comment by obskyr** [comment]
If you're typing directly into the command line, copy this:

```bat
for /F "tokens=*" %A in (input.txt) do python khinsider.py %A
```

If you're putting it in a .bat, instead copy this:

```bat
for /F "tokens=*" %%A in (input.txt) do python khinsider.py %%A
```

Note that none of them have "`khinsider.py`" in the *beginning* - the first word should be "for".

**Comment by G9512** [comment]
thank you, it works, but it doesn't download the cover art

**Comment by obskyr** [comment]
Oh, for what soundtrack?

**Comment by G9512** [comment]
All. I've tried with at least 20 soundtracks.



Oh, for what soundtrack?

-

**Comment by obskyr** [comment]
Can you give me an example of a soundtrack it doesn't download the cover art for?

**Comment by G9512** [comment]
http://downloads.khinsider.com/game-soundtracks/album/evangelion-death

http://downloads.khinsider.com/game-soundtracks/album/lupin-iii-theme-collection

And so on

Can you give me an example of a soundtrack it doesn't download the cover art for?

-

**Comment by obskyr** [comment]
Those soundtracks don't have cover art files. Compare, for example, [Unholy Heights](http://downloads.khinsider.com/game-soundtracks/album/unholy-heights) - there's an image on that page, while the ones you've linked don't have cover art attached.

**Comment by G9512** [comment]
Sorry.

Inviato da iPhone

Il giorno 20 set 2016, alle ore 18:59, obskyr <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Those soundtracks don't have cover art files. Compare, for example, Unholy Heights<http://downloads.khinsider.com/game-soundtracks/album/unholy-heights> - there's an image on that page, while the ones you've linked don't have cover art attached.

-

**Comment by obskyr** [comment]
Oh, no problem! Glad I could clear things up. What I generally do for soundtracks without cover art is I download the cover art from the web manually, and use [MP3TAG](http://www.mp3tag.de/) or something similar to re-tag the songs. If any other issues come up, I'll still be here.
