### ISSUE TITLE
Can't download certains OSTs

### ISSUE THREAD

**Issue by PauloVRefatti** [obskyr/khinsider#18]
I've been trying to download the OSTs from this 3 links:
https://downloads.khinsider.com/game-soundtracks/album/pokemon-emerald-gameboy-advance-gamerip
https://downloads.khinsider.com/game-soundtracks/album/klonoa-of-the-wind-door-to-phantomile
https://downloads.khinsider.com/game-soundtracks/album/klonoa-2-lunatea-s-veil-music-collection
using standard command python khinsider.py name-of-the-link, but all of the three returned the following error:

Traceback (most recent call last):
   File "khinsider.py", line 489, in <module>
     dolt()
   File "khinsider.py", line 487, in dolt
      raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

I'm using python 2.7.13 and the lastest commit of khinsider.py, also, being using this script for months and I think it's great, I really enjoyed it

**Comment by obskyr** [comment]
First of all: excellent taste you got there! The Klonoa games' soundtracks are wonderful.

Looks like KHInsider updated its layout a bit, so I'll need to handle that. One fix, coming right up!
