### ISSUE TITLE
A problem with downloading

### ISSUE THREAD

**Issue by Piripetto** [obskyr/khinsider#21]
The script runs great, but I get this error on this specific link 
https://downloads.khinsider.com/game-soundtracks/album/super-famicom-magazine-vol.7

![memelandia_3444](https://user-images.githubusercontent.com/37277317/37259330-20a4a402-2585-11e8-8db2-0bd0d590cb33.png)

**Comment by Piripetto** [comment]
Holy, don't mind me, I used an old version lol

**Comment by obskyr** [comment]
@Piripetto Oh! Okay, I guess problems sometimes solve themselves, huh. Thanks for taking the time to report it, anyway! 😁
