### ISSUE TITLE
false title name

### ISSUE THREAD

**Issue by LucyDemooon** [obskyr/khinsider#22]
hey,

i get this issue when downloading anything. with numbers in track title 

```
python khinsider.py onigiri
Getting song list...
Downloading 01/14: .mp3...
Skipping over 02/14: .mp3. Already exists.
Skipping over 03/14: .mp3. Already exists.
Skipping over 04/14: .mp3. Already exists.
Skipping over 05/14: .mp3. Already exists.
Skipping over 06/14: .mp3. Already exists.
Skipping over 07/14: .mp3. Already exists.
Skipping over 08/14: .mp3. Already exists.
Skipping over 09/14: .mp3. Already exists.
Skipping over 10/14: .mp3. Already exists.
Skipping over 11/14: .mp3. Already exists.
Skipping over 12/14: .mp3. Already exists.
Skipping over 13/14: .mp3. Already exists.
Skipping over 14/14: .mp3. Already exists.

```

**Comment by obskyr** [comment]
Oh, that's really silly. Onigiri's songs *have no names* in the KHInsider interface. I've fixed it - download the latest version and it should work just fine!

By the way, good choice there with Onigiri! :grin: I like that soundtrack a lot - especially the opening song.

**Comment by LucyDemooon** [comment]
nice that was fast :)
i love the track 8 from Onigiri. Shamisen instrument is so nice.

**Comment by obskyr** [comment]
Ah, in "サラマンダーより強い"? Yeah! I love the shamisen! The mix between hard rock and traditional instruments is super sweet.

There's some shakuhachi in some of the songs, too, if I recall correctly, which I thought was a really nice touch.

**Comment by LucyDemooon** [comment]
yes in this track. 
If you love traditional music + rock, "Wagakki Band" could be something for you.

**Comment by obskyr** [comment]
Oho! 和楽器バンド, I assume? I hadn't heard of them. I'll check them out - thanks a lot for the recommendation!

**Comment by LucyDemooon** [comment]
yes, thats right

**Comment by obskyr** [comment]
I had a listen - that's *really* cool! Thanks! :grin:

**Comment by LucyDemooon** [comment]
no problem ^^ i love Japanese music + anime and food
