### ISSUE TITLE
Support pip 10

### ISSUE THREAD

**Issue by mclark-newvistas** [obskyr/khinsider#25]
```
~/M/a/khinsider$ python khinsider.py starcraft-game-rip
Installing beautifulsoup4...
Traceback (most recent call last):
  File "khinsider.py", line 55, in <module>
    installRequiredModules(needed)
  File "khinsider.py", line 45, in installRequiredModules
    installModules(neededInstalls(), verbose)
  File "khinsider.py", line 42, in installModules
    install(module[1])
  File "khinsider.py", line 37, in install
    pip.main(['install', '--quiet', package])
AttributeError: module 'pip' has no attribute 'main'
$ pip --version
pip 10.0.1 from /usr/lib/python3.6/site-packages/pip (python 3.6)
```

Might be useful: https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program
Also might be useful as a hack :/ : https://stackoverflow.com/a/49853826/118153

**Comment by obskyr** [comment]
Oh, I've actually already fixed this in f4a578b! If you try the latest version, does it work for you?

**Comment by Iiridayn** [comment]
Ah, forgot to update first. Sorry about that, and thank you :).

**Comment by mclark-newvistas** [comment]
Ah, forgot to update first. Sorry about that, and thank you! :). Have you considered putting this in as an adapter for `youtube-dl`?
