### ISSUE TITLE
Generally not working

### ISSUE THREAD

**Issue by HouleWilliam** [obskyr/khinsider#26]
No matter what I do, when the script finds a valid soundtrack and tries to get the song list, the following error message prints:

```
Traceback (most recent call last):
  File "khinsider.py", line 501, in <module>
    sys.exit(doIt())
  File "khinsider.py", line 467, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "khinsider.py", line 359, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "khinsider.py", line 287, in download
    for song in self.songs:
  File "khinsider.py", line 135, in lazyVersion
    setattr(self, attrName, func(self))
  File "khinsider.py", line 249, in songs
    table = self._contentSoup.find('table', id='songlist')
  File "khinsider.py", line 135, in lazyVersion
    setattr(self, attrName, func(self))
  File "khinsider.py", line 232, in _contentSoup
    if contentSoup.find('p').string == "No such album":
AttributeError: 'NoneType' object has no attribute 'string'
```

**Comment by obskyr** [comment]
Hmm, I can't reproduce this...

First of all make sure you've got the latest version. Once you have, it'd be cool if you could tell me:

* What OS you're on
* What Python version you're on (run `python -V` or `py -V`)
* A specific command that breaks (e.g. `khinsider.py disgaea-hour-of-darkness-soundtrack`)

I'll get to fixin' it as soon as I know what causes it!

**Comment by HouleWilliam** [comment]
-Windows 10 V.10.0.15063 (yes it might not be the latest version but I'm sure it's not causing the problem)
-Python 2.7
-python khinsider.py kid-icarus-uprising-original-soundtrack
( also tried other soundtracks, but it only does the error if it's a valid one)

I'm also on the lastest version of your script if that helps. I was on an older version from about 6 months ago I think and I came here to grab the latest to see if it would fix my problem.

**Comment by obskyr** [comment]
Hmm. Can you paste me the output from these two following commands?

```
pip show beautifulsoup4
pip show requests
```

**Comment by HouleWilliam** [comment]
Sorry for the late reply, I'm a bit busy these days.

1. Name: beautifulsoup4
Version: 4.6.0
Summary: Screen-scraping library
Home-page: http://www.crummy.com/software/BeautifulSoup/bs4/
Author: Leonard Richardson
Author-email: leonardr@segfault.org
License: MIT
Location: c:\python27\lib\site-packages
Requires:
c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2. Name: requests
Version: 2.7.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: c:\python27\lib\site-packages
Requires:
c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by obskyr** [comment]
That is very, very strange... With the same factors, I can't trigger the bug. Windows 10, Python 2.7.14, and the same versions of BS4 and requests.

Try the following commands and then `khinsider.py` again:

```
pip install --upgrade beautifulsoup4
pip install --upgrade requests
pip install --upgrade requests[security]
```

**Comment by HouleWilliam** [comment]
I've looked up this long error log on the internet and it seems that it's a conflict between python versions greater and lower 2.7.9. Might try reinstalling python at this point honestly...

**Comment by obskyr** [comment]
Ah, I see. Upgrading Python was probably best, but for posterity, I think using `--trusted-host` to install `requests[security]` would also have solved it (as that makes pip ignore certain SSL problems):

```
pip install --trusted-host pypi.python.org --upgrade requests[security]
```

Thanks for the detailed info! Super helpful. And thanks for using `khinsider.py`!
