### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by Stusbu** [obskyr/khinsider#29]
Was trying to download [Rhythm Thief's OST](https://downloads.khinsider.com/game-soundtracks/album/rhythm-thief-the-emperor-s-treasure), and got a unicode error. 

````
Traceback (most recent call last):
  File "C:\khinsider-master\khinsider.py", line 548, in <module>
    sys.exit(doIt())
  File "C:\khinsider-master\khinsider.py", line 498, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=Tru
e)
  File "C:\khinsider-master\khinsider.py", line 383, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbos
e)
  File "C:\khinsider-master\khinsider.py", line 307, in download
    files.extend(self.images)
  File "C:\khinsider-master\khinsider.py", line 135, in lazyVersion
    setattr(self, attrName, func(self))
  File "C:\khinsider-master\khinsider.py", line 278, in images
    images = [File(urljoin(self.url, url)) for url in urls]
  File "C:\khinsider-master\khinsider.py", line 361, in __init__
    self.filename = unquote(str(url.rsplit('/', 1)[-1]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\uff5e' in position 1
0: ordinal not in range(128)
````

I looked around the issues section and it may be an error on my part, I'm not sure. Just posting it here in case it isn't since it seems like you've fixed a lot of unicode errors. A quick google said that "u'\uff5e'" was the character "~" if that helps.

**Comment by obskyr** [comment]
As I stand on the brink of the mouth of Hell, God's almighty boot ready to bring upon me the ultimate punt, I will ask him: "Why, God? What have I done to deserve this?" He will answer, "Though your sins are pardoned, the Unicode errors have blackened your soul." As I fall into the depths, I will contemplate my life. Tears streaming off my face, falling beside me like empathic raindrops, I will realize: what God told me is true. The Unicode errors turned me into but a husk of what I once was; a hateful creature no longer trusting in the righteousness that is Unicode.

The bug has been fixed!

**Comment by Stusbu** [comment]
Thanks man, very quick response as well. Just tested it out, and works perfectly!
