### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Lapraniteon** [obskyr/khinsider#39]
I get this error message when trying to download from this url: https://downloads.khinsider.com/game-soundtracks/album/legend-of-zelda-takt-of-wind-original-sound-tracks (so i put in _legend-of-zelda-takt-of-wind-original-sound-tracks_):

> Traceback (most recent call last):
  File "khinsider.py", line 589, in <module>
    sys.exit(doIt())
  File "khinsider.py", line 533, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "khinsider.py", line 408, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "khinsider.py", line 323, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "khinsider.py", line 168, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range

**EDIT: This error occurs regardless of which url I am using. It always appears**

**Comment by obskyr** [comment]
This is most likely issue #36, which was fixed in the latest commit. Try downloading the latest version and see if it works, and report back!

**Comment by obskyr** [comment]
Have you tried the new version? I'm almost certain that's the issue – I'll close this issue in a bit if there don't seem to be further problems. Do comment if the problem persists, though!

**Comment by DavidResin** [comment]
@obskyr I had the issue and downloaded the last version. However now it simply stalls on `Getting song list...` seemingly forever. Do you have any idea why? Thanks a lot for all your hard work!
