### ISSUE TITLE
Unexpected Error w/ Error Message Included

### ISSUE THREAD

**Issue by soysocks** [obskyr/khinsider#42]
In an attempt to download the soundtrack for Phoenix Wright Ace Attorney, the following error was returned to me.

I'm using windows 10 home 64-bit, and am performing this scripting action in Windows Powershell. I've successfully downloaded several albums using this script before, so this is not a first-time error.

Here is the error that was returned to me in Powershell:

```
PS C:\Users\roblh\Music\Add to Phone> .\khinsider --format "flac,mp3" phoenix-wright-ace-attorney-ost
Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/khinsider/issues.
Attach the following error message:

Traceback (most recent call last):
  File "C:\Users\roblh\Music\Add to Phone\khinsider.py", line 589, in <module>
    sys.exit(doIt())
  File "C:\Users\roblh\Music\Add to Phone\khinsider.py", line 533, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "C:\Users\roblh\Music\Add to Phone\khinsider.py", line 408, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "C:\Users\roblh\Music\Add to Phone\khinsider.py", line 323, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "C:\Users\roblh\Music\Add to Phone\khinsider.py", line 175, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range
```

**Comment by vtdiep** [comment]
Seems like a similar issue to #36 perhaps.
Changing `ost` to `soundtracks` seems to work.
https://github.com/obskyr/khinsider/blob/870b74f3970953d8af92928150e4ae99a2785bbf/khinsider.py#L364

**Comment by soysocks** [comment]
Seems like that worked! I wonder if it's because the url name for the album included the word "ost" in it. Either way, thank you!

**Comment by obskyr** [comment]
It looks like KHInsider changed their hosting solution for the first time… ever, probably! I'll fix that up in a jiffy.
