### ISSUE TITLE
This ain't it chief.

### ISSUE THREAD

**Issue by Yoshi1203** [obskyr/khinsider#43]
Traceback (most recent call last):
  File "khinsider.py", line 589, in <module>
    sys.exit(doIt())
  File "khinsider.py", line 533, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "khinsider.py", line 408, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "khinsider.py", line 323, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "khinsider.py", line 168, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range

**Comment by Zindswini** [comment]
+1

**Comment by Zindswini** [comment]
I got the same error, downloaded the latest update, started working.

**Comment by obskyr** [comment]
@Yoshi1203 This is *probably* #42 – could you download the latest version, see if that work, and report back?

**Comment by Yoshi1203** [comment]
> @Yoshi1203 This is _probably_ #42 – could you download the latest version, see if that work, and report back?

Yeah, that solved it, thanks.
