### ISSUE TITLE
Can't download any OST's

### ISSUE THREAD

**Issue by lilbud** [obskyr/khinsider#44]
I am using windows 10 with python 3.8.2

No matter which method I use, no ost's will download. I tried using the CMD, I also tried using the module method, but I get constant syntax errors about the equal signs for 'format-order and make-dirs'. If I try to specify downloading the FLAC version of an OST, another window pops up for half a second and closes.

Some commands I've tried running, and the results
"khinsider.py --format flac persona-5" -- windows pops up and closes
"khinsider.download(persona-5[, path="", makeDirs=True, formatOrder=['flac'], verbose=True])" -- Invalid syntax for every equal sign.

Thanks in advance for any help you can provide

**Comment by vtdiep** [comment]
I haven't tried the module method, but maybe I can help regarding cmd

What do you get when you run khinsider.py in cmd with no arguments (Please include the exact command you used, ie everything typed in)

Please include the command along with its response/error;
screenshots might be helpful

**Comment by lilbud** [comment]
On the CMD, navigating to the directory and entering "khinsider.py" returns nothing.
![image](https://user-images.githubusercontent.com/9311410/75640955-b4226900-5c04-11ea-980c-4a831aef81f9.png)

**Comment by vtdiep** [comment]
Assuming you have python added to your PATH, can you try adding "python" or "py" or "py -3" in front of that command?
as in "py -3 khinsider.py"

Does anything change?

**Comment by lilbud** [comment]
> 
> 
> Assuming you have python added to your PATH, can you try adding "python" or "py" or "py -3" in front of that command?
> as in "py -3 khinsider.py"
> 
> Does anything change?

Doing it that way works perfectly, thanks!

**Comment by obskyr** [comment]
Oh hey, big thanks for helping out, @vtdiep!

@lilbud Lemme know if you have any other troubles!

**Comment by lilbud** [comment]
I don't know if that's common sense or not, but maybe that should be added to the readme file. Putting "py -3" before running the file.
