### ISSUE TITLE
CMD window opens and immediately closes and I dont know why

### ISSUE THREAD

**Issue by wumbo-bob** [obskyr/khinsider#49]
I was watching a tutorial ( https://www.youtube.com/watch?v=h5eoBfmWNYA ) and every time I run `.\khinsider.py battlefield-hardline` in the correct directory via admin powersell, a CMD window opens and closes immediately after. Also, I am very inept when it comes to coding, in fact, I pretty much dont know anything.

**Comment by bt2901** [comment]
Try the following.

1) Open the correct directory in Windows Explorer
2) Click on the address bar (it should transform into a string like `C:\<something>\<something>\`) OR press Ctrl+C
3) write `cmd` and press Enter
4) in the CMD window just opened, write `./khinsider.py`, or `python khinsider.py` or `python3 khinsider.py` -- whatever works for you.
5) I don't promise that it will work, but that way we are going to see an entire error message at least.
