### ISSUE TITLE
Can't seem to get download path to work

### ISSUE THREAD

**Issue by TitanKyojin** [obskyr/khinsider#51]
By default it downloads to my user folder but I'd like to make my music folder the default. Is there a way to do this?

**Comment by obskyr** [comment]
Hi! Which operating system are you on?

**Comment by TitanKyojin** [comment]
Hello, I'm using Windows 10.

**Comment by BlastoiseVeteran** [comment]
Save khinsider.py into your music folder and run it inside of there instead of running it inside your user folder.

**Comment by obskyr** [comment]
Closing this as it seems to be more or less solved. Feel free to comment if you'd like it reopened!
