### ISSUE TITLE
Not working on Windows 10 on latest version of Python

### ISSUE THREAD

**Issue by gillmi** [obskyr/khinsider#53]
Yeah... whenever I run the program it says the syntax in invalid, even when copy and pasting it into the command line.

**Comment by obskyr** [comment]
Try prepending `py` (e.g. `py khinsider.py jumping-flash`) – sometimes, the PATH environment variable on Windows can be a bit mucked up.

I'll close this as it's a bit of an old issue and not really an issue with the script so much as with the environment – feel free to comment if you'd still like help, though!
