### ISSUE TITLE
Khinsider down? Or just me?

### ISSUE THREAD

**Issue by ghost** [obskyr/khinsider#54]
Khinsider no longer loads any song on the website. I tried on my browser first, everything works fine until I clicked on any album. 

The mini player that controls the audio, try to load, but it's just do that indefinitely. I tried everything to make the audio play: Clicked on the song title; clicked on the "Click here to download as MP3"...

Nothing, It just trying to load a song infinity.

I tried on another browser, and... same results.

Now, I tried using the script. It works until the process of download: 

Downloading Banjo-Tooie CD Soundtrack: 

> Downloading 01/15: 01 - Jinjo Village.mp3...
Couldn't download 01 - Jinjo Village.mp3. Trying again...
Couldn't download 01 - Jinjo Village.mp3. Trying again...
Couldn't download 01 - Jinjo Village.mp3. Skipping over.
Downloading 02/15: 02 - Isle of Hags.mp3...
Couldn't download 02 - Isle of Hags.mp3. Trying again...
Couldn't download 02 - Isle of Hags.mp3. Trying again...
Couldn't download 02 - Isle of Hags.mp3. Skipping over.

This is on Termux (Android).

Anyone has the same problem as me?

**Comment by gabrielBitts** [comment]
I'm actually having the same issue as you @MTSYuki

**Comment by MTSYuki** [comment]
> I'm actually having the same issue as you @MTSYuki 

Even when you try to play a song in your Browser?

**Comment by Ghost325** [comment]
I'm having the same problem...

**Comment by junenewflavor** [comment]
Same here :(

**Comment by MTSYuki** [comment]
Okay so, after monitoring the website traffic, I just encountered that the audio is coming from a website called
`https://vgmsite.com/<name_of_soundtrack>/`

So, I visited [https://downforeveryoneorjustme.com/vgmsite.com?proto=https](Down for everyone or just me) to see if the server is running.

For some reason, the server is running but when I visited the vgmsite, the page is trying load for much time that returns ERR_CONNECTION_TIMED_OUT.

Can anyone open the `Down for everyone or just me` link and see if the results is the same as me?

**Comment by neurotech** [comment]
> It's just you. vgmsite.com is up.

**Comment by MTSYuki** [comment]
@neurotech Same here

**Comment by obskyr** [comment]
Closing this as it seems to have been a temporary issue with KHInsider, rather than an issue with the script. Feel free to comment if the problem reappears!
