### ISSUE TITLE
Show Current Download Speed and Percentage Completion of each Soundtrack

### ISSUE THREAD

**Issue by y3hy3h** [obskyr/khinsider#6]
Request as title

Thanks
Love your script so much

**Comment by obskyr** [comment]
Download speed is a bit overkill, I think, but what I *have* been thinking about is showing the progress through the soundtrack. In how many songs you've downloaded out of how many there are (e.g. `5/32` or `26/27`), and not in percentage form, as the former is considerably more useful. May get on that soon.

Thanks for the request!
