### ISSUE TITLE
On some URLs, 'info' is appended to the title of the Soundtrack

### ISSUE THREAD

**Issue by JComins000** [obskyr/khinsider#91]
line 302 needs to be changed.
```
        return self._contentSoup.find('h2').get_text(strip=True)
```
should be
```
        return self._contentSoup.find('h2').get_text(strip=True).rstrip('info')
```

This is what the heading looks like in a breakpoint. There might be some other way to capture the `h2` without capturing the `a`, but `rstrip` was the easiest suggestion for me to make.

```
(Pdb) self._contentSoup.find('h2')
<h2>F-Zero Climax<a href="https://vgmsite.com/soundtracks/f-zero-climax-gba/khinsider.info.txt" target="_blank"><i class="material-icons txt_info_file">info</i></a></h2>
```

https://downloads.khinsider.com/game-soundtracks/album/f-zero-climax-gba
https://i.imgur.com/GIvnvo8.png

**Comment by obskyr** [comment]
Thank you for the report! :blush:
